name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code (optional, for context in future steps)
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Validate PR title and description
      - name: Validate PR title and description
        uses: actions/github-script@v6
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const issuePattern = /^\[Issue #\d+\] .+/;

            if (!prTitle.match(issuePattern)) {
              core.setFailed(
                "Pull request title must start with '[Issue #<number>]' format (e.g., '[Issue #123] Add new feature')."
              );
            }

